"""Graph assembly.

The pipeline shape is decided here from the feature flags, so a run with audit and
review disabled is a genuinely smaller graph rather than the same graph with
no-op nodes. The reviewer gate is a real `interrupt()`: after the human corrects
and resumes, control returns to the gate, which loops back through the engine once
(so corrected inputs are recomputed and re-scored) and then continues to the
report.

    intake ─blocked──────────────────────────────────────────────────────┐
       │                                                                  │
    extract → classify → research → calculate → audit → summarize → review_gate
                                        ▲                              │  │
                                        └──corrections─────────────────┘  │ (approved / none)
                                                                          ▼
                                        report → guardrail_output → finalize → END
"""

from __future__ import annotations

from functools import lru_cache
from typing import Literal

from langgraph.checkpoint.memory import MemorySaver
from langgraph.checkpoint.serde.jsonplus import JsonPlusSerializer
from langgraph.graph import END, START, StateGraph

from taxpilot.config import Settings, get_settings
from taxpilot.graph import nodes
from taxpilot.graph.state import TaxState


def _model_types() -> list[tuple[str, str]]:
    """Every (module, class) pair the checkpointer may need to reconstruct.

    The serializer matches on the full (module, name) key, so registering the
    module alone does nothing - each class is listed. Generated by reflection so a
    new model in taxpilot.models is covered automatically.
    """
    import enum
    import inspect

    from pydantic import BaseModel

    import taxpilot.models as models

    pairs: list[tuple[str, str]] = []
    for name, obj in vars(models).items():
        if inspect.isclass(obj) and obj.__module__ == "taxpilot.models" and (
            issubclass(obj, BaseModel) or issubclass(obj, enum.Enum)
        ):
            pairs.append(("taxpilot.models", name))
    return pairs


def _memory_checkpointer() -> MemorySaver:
    """MemorySaver that reconstructs our models across a review resume.

    The reviewer gate checkpoints state holding pydantic models and enums;
    registering their exact types makes the serializer rebuild them (rather than
    hand a node a bare dict) and stays correct when a future LangGraph blocks
    unregistered types outright.
    """
    serde = JsonPlusSerializer(allowed_msgpack_modules=_model_types())
    return MemorySaver(serde=serde)


def after_intake(state: TaxState) -> Literal["extract", "end"]:
    return "end" if state.get("blocked") else "extract"


def after_review(state: TaxState) -> Literal["calculate", "report"]:
    # `recompute` is set only when a correction changed an engine input; the gate
    # has already set reviewed=True, so the recompute pass cannot interrupt again
    # and clears `recompute`, which is what ends the loop.
    return "calculate" if state.get("recompute") else "report"


def build_graph(settings: Settings | None = None, *, checkpointer=None):
    """Compile the pipeline. A checkpointer is required for the reviewer gate."""
    settings = settings or get_settings()
    graph = StateGraph(TaxState)

    graph.add_node("guardrail_intake", nodes.guardrail_intake_node)
    graph.add_node("extract", nodes.extract_node)
    graph.add_node("classify", nodes.classify_node)
    graph.add_node("research", nodes.research_node)
    graph.add_node("calculate", nodes.calculate_node)
    graph.add_node("summarize", nodes.summarize_node)
    graph.add_node("report", nodes.report_node)
    graph.add_node("guardrail_output", nodes.guardrail_output_node)
    graph.add_node("finalize", nodes.finalize_node)

    graph.add_edge(START, "guardrail_intake")
    graph.add_conditional_edges(
        "guardrail_intake", after_intake, {"extract": "extract", "end": "finalize"}
    )
    graph.add_edge("extract", "classify")
    graph.add_edge("classify", "research")
    graph.add_edge("research", "calculate")

    # The summary is written before the review gate so it is visible both while a
    # return awaits human review and after approval; the recompute loop passes
    # back through it, so corrected figures get a fresh summary.
    post_calc = "audit" if settings.enable_audit else "summarize"
    graph.add_edge("calculate", post_calc)

    if settings.enable_audit:
        graph.add_node("audit", nodes.audit_node)
        graph.add_edge("audit", "summarize")

    graph.add_edge("summarize", "review_gate" if settings.enable_review else "report")

    if settings.enable_review:
        graph.add_node("review_gate", nodes.review_gate_node)
        graph.add_conditional_edges(
            "review_gate", after_review, {"calculate": "calculate", "report": "report"}
        )

    graph.add_edge("report", "guardrail_output")
    graph.add_edge("guardrail_output", "finalize")
    graph.add_edge("finalize", END)

    return graph.compile(checkpointer=checkpointer or _memory_checkpointer())


@lru_cache
def get_graph():
    """Process-wide compiled graph with an in-memory checkpointer.

    In-memory means a paused review is lost on restart; point this at
    langgraph-checkpoint-postgres for a deployment with more than one worker.
    """
    return build_graph()
